# 基础部分：

## 数组运算

In [4]:
import numpy as np
#生成一维示例数组
a = np.array([10,20,30,40,50])
#从1开始创建小于6的数组
b = np.arange(1,6)
a, b

(array([10, 20, 30, 40, 50]), array([1, 2, 3, 4, 5]))

In [6]:
#一维数组加减法运算
a + b
a - b


array([ 9, 18, 27, 36, 45])

In [7]:
a * b

array([ 10,  40,  90, 160, 250])

In [8]:
a / b

array([10., 10., 10., 10., 10.])

In [9]:
#生成二维示例数组（可看出矩阵）
A = np.array([[1,2],
             [3,4]])
B = np.array([[5,6],
             [7,8]])
A,B

(array([[1, 2],
        [3, 4]]), array([[5, 6],
        [7, 8]]))

In [10]:
A + B

array([[ 6,  8],
       [10, 12]])

In [11]:
A - B 

array([[-4, -4],
       [-4, -4]])

In [12]:
A * B

array([[ 5, 12],
       [21, 32]])

In [13]:
#矩阵乘法
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [14]:
#如果使用np.mat将二维数组定义为矩阵，则可以直接使用*来进行矩阵乘法
np.mat(A)*np.mat(B)

matrix([[19, 22],
        [43, 50]])

In [15]:
2 * A


array([[2, 4],
       [6, 8]])

In [16]:
#矩阵转置
A.T

array([[1, 3],
       [2, 4]])

In [17]:
#矩阵求逆
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### 数学函数

In [18]:
#三角函数
print(a)

np.sin(a)

[10 20 30 40 50]


array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [19]:
#以自然对数为底的指数函数
np.exp(a)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21])

In [20]:
#数组的方根的运算（开平方）
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [23]:
#数组的立方运算
np.power(a, 3)

array([  1000,   8000,  27000,  64000, 125000], dtype=int32)

### 数组切片和索引

In [27]:
#一维数组索引
a = np.array([1,2,3,4,5])
a[0], a[-1], a[-2]

(1, 5, 4)

In [28]:
#一维数组切片
a[0:2],a[:-1]

(array([1, 2]), array([1, 2, 3, 4]))

In [31]:
#二维数组索引
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
a[0],a[2],a

(array([1, 2, 3]), array([7, 8, 9]), array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [34]:
#二维数组切片
print(a)
#取索引为1的列
a[:, 0]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 4, 7])

In [35]:
a[1:3,:]

array([[4, 5, 6],
       [7, 8, 9]])

### 数组形状操作

In [38]:
#生成二维示例数组
a = np.random.random((3,2))
a

array([[0.86709453, 0.67071874],
       [0.04277306, 0.77831926],
       [0.32952483, 0.73084241]])

In [39]:
#查看数组形状
a.shape

(3, 2)

In [40]:
#更改数组形状（不改变原始数组）
a.reshape(2,3)

array([[0.86709453, 0.67071874, 0.04277306],
       [0.77831926, 0.32952483, 0.73084241]])

In [41]:
a

array([[0.86709453, 0.67071874],
       [0.04277306, 0.77831926],
       [0.32952483, 0.73084241]])

In [42]:
#更改数组形状（改变原始数组）
a.resize(2,3)

In [43]:
a

array([[0.86709453, 0.67071874, 0.04277306],
       [0.77831926, 0.32952483, 0.73084241]])

In [44]:
#展平数组
a.ravel()

array([0.86709453, 0.67071874, 0.04277306, 0.77831926, 0.32952483,
       0.73084241])

In [46]:
#垂直拼合数组
a = np.random.randint(5, size=(3, 3))
b = np.random.randint(5, size=(3, 3))

a,b

(array([[1, 0, 4],
        [0, 3, 4],
        [4, 0, 2]]), array([[3, 2, 2],
        [4, 2, 3],
        [0, 1, 3]]))

In [47]:
np.vstack((a,b))

array([[1, 0, 4],
       [0, 3, 4],
       [4, 0, 2],
       [3, 2, 2],
       [4, 2, 3],
       [0, 1, 3]])

In [48]:
#水平拼合数组
np.hstack((a,b))

array([[1, 0, 4, 3, 2, 2],
       [0, 3, 4, 4, 2, 3],
       [4, 0, 2, 0, 1, 3]])

In [49]:
#沿横轴分割数组
np.hsplit(a, 3)

[array([[1],
        [0],
        [4]]), array([[0],
        [3],
        [0]]), array([[4],
        [4],
        [2]])]

In [53]:
#沿纵轴分割数组
np.vsplit(a,3)

[array([[1, 0, 4]]), array([[0, 3, 4]]), array([[4, 0, 2]])]

### 数组排序

In [54]:
#生成示例数组
a = np.array(([1,4,3],[6,2,9],[4,7,2]))
a

array([[1, 4, 3],
       [6, 2, 9],
       [4, 7, 2]])

In [59]:
#返回每列最大值
np.max(a, axis=0)

array([6, 7, 9])

In [60]:
#返回每行最小值
np.min(a, axis=1)

array([1, 2, 2])

In [61]:
#返回每列最大值的索引
np.argmax(a, axis=0)

array([1, 2, 1], dtype=int64)

In [62]:
#返回每行最小值的索引
np.argmin(a, axis=1)

array([0, 1, 2], dtype=int64)

### 数组统计

In [63]:
#统计数组各列中的中位数
np.median(a, axis=0)

array([4., 4., 3.])

In [65]:
#统计数组各列的算术平均数
np.mean(a ,axis=0)

array([3.66666667, 4.33333333, 4.66666667])

In [66]:
#统计数组各列加权平均值
np.average(a, axis=0)

array([3.66666667, 4.33333333, 4.66666667])

In [67]:
#统计各行的方差
np.var(a, axis=1)

array([1.55555556, 8.22222222, 4.22222222])

In [68]:
#统计数组各列的标准偏差
np.std(a, axis=0)

array([2.05480467, 2.05480467, 3.09120617])

# 进阶部分

In [69]:
#创建一个5*5的二维数组，其中边界为1，其余值为0
Z = np.ones((5,5))
Z[1:-1,1:-1] = 0
Z

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [70]:
#使用数字0将一个全为1的二维数组包围
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
Z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [75]:
#创建一个5*5的二维数组，并设置值1,2,3,4落在其对角线下方
Z = np.diag(1+np.arange(4),k=-1)
Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [77]:
#创建一个10*10的二维数组，并使得1和0沿对角线间隔放置
#实际上就是在行和列分别间隔两个元素填数
Z = np.zeros((10,10),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 0
Z

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]])

In [78]:
#创建以0-10的一维数组，并将（1,9]之间的书全部反转成负数
Z = np.arange(11)
Z[(1 < Z) & (Z <= 9)] *= -1
Z

array([ 0,  1, -2, -3, -4, -5, -6, -7, -8, -9, 10])

In [79]:
#找出两个一维数组中相同的元素
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print("Z1:", Z1)
print("Z2:", Z2)
np.intersect1d(Z1,Z2)

Z1: [4 4 3 5 7 5 8 3 9 1]
Z2: [8 9 3 6 4 2 7 0 0 7]


array([3, 4, 7, 8, 9])

In [81]:
#使用numpy打印昨天、今天、明天的日期
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("yesterday:", yesterday)
print("today:", today)
print("tomorrow:", tomorrow)

yesterday: 2018-07-15
today: 2018-07-16
tomorrow: 2018-07-17


In [83]:
#使用五种不同的方法提取一个随机数组的整数部分
Z = np.random.uniform(0,10,10)
print("原始值：", Z)
print("method 1:", Z - Z%1)
print("method 2:", np.floor(Z))
print("method 3:", np.ceil(Z) - 1)
print("method 4:", Z.astype(int))
print("method 5:", np.trunc(Z))
B = Z%1
B

原始值： [2.79746275 9.31208219 5.05067344 2.88510077 5.9665867  2.27437888
 7.45041671 8.73671382 0.56499185 6.20621494]
method 1: [2. 9. 5. 2. 5. 2. 7. 8. 0. 6.]
method 2: [2. 9. 5. 2. 5. 2. 7. 8. 0. 6.]
method 3: [2. 9. 5. 2. 5. 2. 7. 8. 0. 6.]
method 4: [2 9 5 2 5 2 7 8 0 6]
method 5: [2. 9. 5. 2. 5. 2. 7. 8. 0. 6.]


array([0.79746275, 0.31208219, 0.05067344, 0.88510077, 0.9665867 ,
       0.27437888, 0.45041671, 0.73671382, 0.56499185, 0.20621494])

In [84]:
#创建一个5*5的矩阵，其中每行的数值范围从1到5
Z = np.zeros((5,5))
Z += np.arange(1,6)

Z

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

In [94]:
#创建一个长度为5的间隔一维数组，其值域范围从0到1，但是不包括0和1
Z = np.linspace(0,1,6,endpoint=False)[1:]

Z

array([0.16666667, 0.33333333, 0.5       , 0.66666667, 0.83333333])